[colors.primary]
background = "#090610"
foreground = "#c1c0c3"

[colors.cursor]
text = "#090610"
cursor = "#c1c0c3"

[colors.vi_mode_cursor]
text = "#090610"
cursor = "#c1c0c3"

[colors.search.matches]
foreground = "#090610"
background = "#c1c0c3"


[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#090610"
red = "#1e0744"
green = "#22165d"
yellow = "#203645"
blue = "#491e60"
magenta = "#2a338c"
cyan = "#4287b3"
white = "#8f8a96"

[colors.bright]
black = "#5c5669"
red = "#5a3c8e"
green = "#5948a9"
yellow = "#447c9f"
blue = "#8e4bb1"
magenta = "#7279c2"
cyan = "#9ebfd5"
white = "#c1c0c3"
