[colors.primary]
background = "#000000"
foreground = "#c3c1c2"

[colors.cursor]
text = "#000000"
cursor = "#c3c1c2"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#c3c1c2"

[colors.search.matches]
foreground = "#000000"
background = "#c3c1c2"


[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#12080b"
red = "#102b2d"
green = "#930e2f"
yellow = "#3f315d"
blue = "#33613c"
magenta = "#53567f"
cyan = "#517e4e"
white = "#968c90"

[colors.bright]
black = "#6a575d"
red = "#387f84"
green = "#bc6379"
yellow = "#7357b7"
blue = "#5ab86e"
magenta = "#868bcb"
cyan = "#86c982"
white = "#c3c1c2"
