[colors.primary]
background = "#0b0a17"
foreground = "#c2c1c5"

[colors.cursor]
text = "#0b0a17"
cursor = "#c2c1c5"

[colors.vi_mode_cursor]
text = "#0b0a17"
cursor = "#c2c1c5"

[colors.search.matches]
foreground = "#0b0a17"
background = "#c2c1c5"


[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0b0a17"
red = "#181a60"
green = "#273381"
yellow = "#324599"
blue = "#37458a"
magenta = "#514163"
cyan = "#5177b7"
white = "#8f8d98"

[colors.bright]
black = "#5b596d"
red = "#494dac"
green = "#6974be"
yellow = "#818ec9"
blue = "#7a86c5"
magenta = "#8d65bd"
cyan = "#acbddb"
white = "#c2c1c5"
