general {
    gaps_in = 4
    gaps_out = 0
    border_size = 2
    resize_on_border = true

    layout = master
    
    col.active_border = rgb(7d766c)
    col.inactive_border = rgb(0b0b1b)
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = false # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    # doesnt work idk why
    mfact = 0.50
    new_status = slave
}



decoration {
    rounding = 0

    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    blur {
        enabled = yes
        size = 8
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }

    # can be used for a cool double border look, however, the gaps space must be increased to acomodate because the shadow is not displayed like borders, it can be be rendered outside the screen or under the bar
    # shadow{
    #     enabled = true
    #     range = 2
    #     sharp = 1
    #     color = rgb(0a0812)
    # }
}



# layerrule = blur,waybar

